approvedGitRepositories:
  - "**"

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmScopes:
  nick8green:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
