-- remove views
DELETE VIEW IF EXISTS `Pages`;
DELETE VIEW IF EXISTS `PageElement`;

-- remove tables
DELETE TABLE IF EXISTS `Config`;
DELETE TABLE IF EXISTS `Content`;
DELETE TABLE IF EXISTS `PageType`;
DELETE TABLE IF EXISTS `Form`;
DELETE TABLE IF EXISTS `Type`;
DELETE TABLE IF EXISTS `PageNavigation`;
DELETE TABLE IF EXISTS `Navigation`;
DELETE TABLE IF EXISTS `Page`;
DELETE TABLE IF EXISTS `User`;
DELETE TABLE IF EXISTS `Audit`;
