# Configuration file version
apiVersion: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  # <string, required> Sets the name you use to refer to
  # the data source in panels and queries.
  - name: Prometheus
    # <string, required> Sets the data source type.
    type: prometheus
    # <string, required> Sets the access mode, either
    # proxy or direct (Server or Browser in the UI).
    # Some data sources are incompatible with any setting
    # but proxy (Server).
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    # <string> Sets the data source's URL, including the
    # port.
    url: http://prometheus:9090
    # <map> Fields to convert to JSON and store in jsonData.
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 3.4.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
