apiVersion: 1

muteTimes:
  - orgId: 1
    name: no_weekends
    time_intervals:
      - weekdays: [saturday, sunday]

policies:
  - orgId: 1
    receiver: email
    group_by:
      - grafana_folder
      - alertname
    routes:
      - receiver: email
        object_matchers:
          - - monitor
            - =
            - testdata
        mute_time_intervals:
          - no_weekends

contactPoints:
  - orgId: 1
    name: email
    receivers:
      - uid: fenixsqo04qo0c
        type: email
        settings:
          addresses: 'alerting-dev@localhost'
          message: '{{ template "custom_email.message" .}}'
          singleEmail: false
          subject: '{{ template "custom_email.subject" .}}'
        disableResolveMessage: false
  # - orgId: 1
  #   name: slack
  #   receivers:
  #     - uid: fenixqohyo0sgc
  #       type: slack
  #       settings:
  #         recipient: alerting-dev
  #         token:
  #       disableResolveMessage: false

templates:
  - orgId: 1
    name: custom_email.message
    template: |
      {{ define "custom_email.message" }}
        Lorem ipsum - Custom alert!
      {{ end }}
  - orgId: 1
    name: custom_email.subject
    template: |
      {{ define "custom_email.subject" }}
      {{ len .Alerts.Firing }} firing alert(s), {{ len .Alerts.Resolved }} resolved alert(s)
      {{ end }}
