{
 "title": "Artillery - http metrics",
 "description": "http metrics",
 "tags": [
  "nodejs",
  "artillery",
  "performance",
  "http"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "test_id", "label": "Select test_id", "query": { "query": "artillery_counters" } },
   { "name": "http_codes", "label": "Select http_code", "query": { "query": "artillery_counters" } }
  ]
 },
 "panels": [
  {
   "title": "http.codes.$http_codes",
   "type": "barchart",
   "description": "Metrics for http.codes",
   "gridPos": { "h": 11, "w": 18, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "artillery_counters{test_id=~\"$test_id\", metric=~\"http_codes_$http_codes\"}"
    }
   ]
  },
  {
   "title": "http.requests",
   "type": "barchart",
   "description": "Metrics for http.requests",
   "gridPos": { "h": 11, "w": 18, "x": 3, "y": 11 },
   "targets": [
    {
     "expr": "artillery_counters{test_id=~\"$test_id\", metric=\"http_requests\"}"
    }
   ]
  },
  {
   "title": "http.response_time",
   "type": "timeseries",
   "description": "Metrics for http.response_time",
   "gridPos": { "h": 12, "w": 18, "x": 3, "y": 22 },
   "targets": [
    {
     "expr": "artillery_summaries{test_id=~\"$test_id\", metric=\"http_response_time_min\"}",
     "legendFormat": "min"
    },
    {
     "expr": "artillery_summaries{test_id=~\"$test_id\", metric=\"http_response_time_max\"}",
     "legendFormat": "max"
    },
    {
     "expr": "artillery_summaries{test_id=~\"$test_id\", metric=\"http_response_time_p95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "artillery_summaries{test_id=~\"$test_id\", metric=\"http_response_time_p99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "http.responses",
   "type": "barchart",
   "description": "Metrics for http.responses",
   "gridPos": { "h": 11, "w": 18, "x": 3, "y": 34 },
   "targets": [
    {
     "expr": "artillery_counters{test_id=~\"$test_id\", metric=\"http_responses\"}"
    }
   ]
  }
 ]
}