{
 "title": "Artillery - vusers metrics",
 "description": "vusers  metrics",
 "tags": [
  "nodejs",
  "artillery",
  "performance",
  "vusers"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "test_id", "label": "Select test_id", "query": { "query": "artillery_counters" } },
   { "name": "vusers_created_by_name", "label": "Select vusers_created_by_name", "query": { "query": "artillery_counters" } }
  ]
 },
 "panels": [
  {
   "title": "vusers.completed",
   "type": "barchart",
   "description": "Metrics for vusers.completed",
   "gridPos": { "h": 11, "w": 18, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "artillery_counters{test_id=~\"$test_id\", metric=\"vusers_completed\"}"
    }
   ]
  },
  {
   "title": "vusers.created",
   "type": "barchart",
   "description": "Metrics for vusers.created",
   "gridPos": { "h": 12, "w": 18, "x": 2, "y": 11 },
   "targets": [
    {
     "expr": "artillery_counters{test_id=~\"$test_id\", metric=\"vusers_created\"}"
    }
   ]
  },
  {
   "title": "vusers_created_by_name(_$vusers_created_by_name)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 18, "x": 2, "y": 23 },
   "targets": [
    {
     "expr": "artillery_counters{test_id=~\"$test_id\", metric=~\"vusers_created_by_name_$vusers_created_by_name\"}"
    }
   ]
  },
  {
   "title": "vusers.failed",
   "type": "barchart",
   "description": "Metrics for vusers_failed",
   "gridPos": { "h": 12, "w": 18, "x": 2, "y": 34 },
   "targets": [
    {
     "expr": "artillery_counters{test_id=~\"$test_id\", metric=\"vusers_failed\"}"
    }
   ]
  },
  {
   "title": "vusers.session_length",
   "type": "timeseries",
   "description": "Metrics for vusers.session_length",
   "gridPos": { "h": 12, "w": 18, "x": 2, "y": 46 },
   "targets": [
    {
     "expr": "artillery_summaries{test_id=~\"$test_id\", metric=\"vusers_session_length_min\"}",
     "legendFormat": "min"
    },
    {
     "expr": "artillery_summaries{test_id=~\"$test_id\", metric=\"vusers_session_length_max\"}",
     "legendFormat": "max"
    },
    {
     "expr": "artillery_summaries{test_id=~\"$test_id\", metric=\"vusers_session_length_p95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "artillery_summaries{test_id=~\"$test_id\", metric=\"vusers_session_length_p99\"}",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}