global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: adequate_app_metrics
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - app:3000 # Domain of your website
        labels:
          service: 'app'
  - job_name: 'pushgateway'
    static_configs:
      - targets:
          - 'pushgateway:9091'
