{
 "title": "Adequate App Metrics",
 "tags": [
  "adequate",
  "app",
  "frontend",
  "nodejs"
 ],
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(nodejs_version_info,service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Request Rate by Route",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (status, route, method) * 60",
     "legendFormat": "{{method}} {{route}} - {{status}}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{service=~\"$service\"}[$__range]))"
    }
   ]
  },
  { "title": "Web Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Cumulative Layout Shift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "targets": [
    { "expr": "web_vitals_cls", "legendFormat": "{{navigationType}}" }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "targets": [
    { "expr": "web_vitals_fid", "legendFormat": "{{navigationType}}" }
   ]
  },
  {
   "title": "First Input Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "targets": [
    { "expr": "web_vitals_fid", "legendFormat": "{{navigationType}}" }
   ]
  },
  {
   "title": "Interaction to Next Paint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    { "expr": "web_vitals_inp", "legendFormat": "{{navigationType}}" }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    { "expr": "web_vitals_lcp / 1000", "legendFormat": "{{navigationType}}" }
   ]
  },
  {
   "title": "Time to First Byte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    { "expr": "web_vitals_ttfb", "legendFormat": "{{navigationType}}" }
   ]
  }
 ]
}