name: cleanup old workflows and images
on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:
    inputs:
      storage-days:
        default: 30
        description: 'Number of days to keep images'
        required: false
        type: number
      successful-workflows:
        default: 10
        description: 'Number of successful workflow runs to keep'
        required: false
        type: number

jobs:
  images:
    name: 🧹 clean up images
    permissions:
      contents: read
      packages: write
    uses: nick8green/workflows/.github/workflows/docker-cleanup.yml@main
    with:
      days: ${{ inputs.storage-days || 30 }}
    secrets:
      token: ${{ secrets.GHCR_PAT }}

  workflows:
    name: 🧹 clean up workflow runs
    permissions:
      contents: read
      actions: write
    uses: nick8green/workflows/.github/workflows/workflow-cleanup.yml@main
    with:
      keep-successful: ${{ inputs.successful-workflows || 10 }}
    secrets:
      token: ${{ secrets.GH_WF_PAT }}
