name: cleanup old workflows and images
on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:
  push:
    branches:
      - update-dockerfiles

jobs:
  images:
    name: 🧹 clean up images
    permissions:
      contents: read
      packages: write
    uses: nick8green/workflows/.github/workflows/docker-cleanup.yml@main
    secrets:
      token: ${{ secrets.GHCR_PAT }}

  workflows:
    name: 🧹 clean up workflow runs
    permissions:
      contents: read
      actions: write
    uses: nick8green/workflows/.github/workflows/workflow-cleanup.yml@main
    secrets:
      token: ${{ secrets.GH_WF_PAT }}
