name: cleanup old ghcr images
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  cleanup:
    name: 🧹 clean up old images
    permissions:
      contents: read
      packages: write
    uses: nick8green/workflows/.github/workflows/docker-cleanup.yml@main
    with:
      pattern: adequate
    secrets:
      token: ${{ secrets.GHCR_PAT }}
